name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/npm@v1
        with:
          args: install
      - uses: actions/npm@v1
        with:
          args: run test